### ISSUE TITLE
What is the license for this code?

### ISSUE THREAD

**Issue by arthurbarr** [leonidlm/packer-builder-softlayer#13]
I can't see what license this code is released under.  It would be helpful to describe this somewhere, especially for any corporate users.

**Comment by leonidlm** [comment]
Hi @arthurbarr,
I just [added a license](https://github.com/leonidlm/packer-builder-softlayer/commit/6d6564934ce38ab609ff73b8e21211864af980fa) (MIT). 

Thank you for your inquiry.
