### ISSUE TITLE
Failure to compile on CentOS 7: undefined packer.ConfigTemplate

### ISSUE THREAD

**Issue by zapman449** [leonidlm/packer-builder-softlayer#21]
Steps to get me here:
1) fresh vagrant box running cent7
2) install go v1.4
3) get packer to build (0.8.6)
4) Find and fix problem with ssh (builder/softlayer/ssh.go builder/softlayer/step_create_ssh_key.go both refer to "code.google.com/p/go.crypto/ssh".  The 'right' version appears to be "golang.org/x/crypto/ssh")
5) clone this repo
6) run this command:

    $ go build -o $GOPATH/bin main.go
    # github.com/leonidlm/packer-builder-softlayer/builder/softlayer
    builder/softlayer/builder.go:45: undefined: packer.ConfigTemplate
    $ echo $?
    2

**Comment by zapman449** [comment]
Close me.  This is a duplicate of #17 

Chased the pull requests and found something that compiles.

**Comment by cmluciano** [comment]
Fixed with aaee0561423ff696e3f516895a9ef671b6d2afd6
