### ISSUE TITLE
Unable to pass further softlayer options to instance creation

### ISSUE THREAD

**Issue by zapman449** [leonidlm/packer-builder-softlayer#23]
Your readme states:

    As already stated above, a good way of reviewing the available options is by inspecting the output of the following API call:

    curl https://<username>:<api_key>@api.softlayer.com/rest/v3/SoftLayer_Account/getCreateObjectOptions.json

(first off, that URL fails against softlayer.  I believe the correct URL would be: https://${SL_USERNAME}:${SL_API_KEY}@api.softlayer.com/rest/v3/SoftLayer_Virtual_Guest/getCreateObjectOptions.json )

Real issue is that I don't see a way though the config or code to pass further options to SL.  Specifically, I'm most interested in setting privateNetworkOnlyFlag to True.  But others will be required.

**Comment by cmluciano** [comment]
That's correct. Would using the env vars be more useful?

**Comment by cmluciano** [comment]
Closing due to staleness
