### ISSUE TITLE
Is it possible to build off of another image in Softlayer?

### ISSUE THREAD

**Issue by ldanielw1** [leonidlm/packer-builder-softlayer#26]
I am currently building off of a clean platform image every time I try to run a packer build with softlayer, but I was wondering if there would be any way for me to launch an image that I have already created, and then make changes via packer. I didn't see any reference to this in the README and was wondering if it's not an option right now or just not in README?

**Comment by cmluciano** [comment]
Yes please take a look here `base_image_id (string) - The ID of the base image to use (usually defined by the globalIdentifier or the uuid fields in SoftLayer API). This is the image that will be used for launching a new instance. NOTE that if you choose to use this option, you must specify a private key using ssh_private_key_file (described below). To view all of your currently available images, run:`

**Comment by ldanielw1** [comment]
This actually still doesn't work for me. I have tried using the image ID number (in the url), using quotes with that number, the name of the image, and still can't get it to work.

I am also not quite understanding what ssh file to use for ssh_private_key_file. What is this for, and is there a specific key I need to use?
