### ISSUE TITLE
Attempting to build fails

### ISSUE THREAD

**Issue by kubilus1** [leonidlm/packer-builder-softlayer#27]
I'm attempting to set up packer-builder-softlayer and get the following errors:

$ sudo go build -o /usr/local/bin/packer-builder-softlayer main.go
builder/softlayer/step_create_ssh_key.go:4:2: cannot find package "code.google.com/p/gosshold/ssh" in any of:
        /usr/lib/golang/src/code.google.com/p/gosshold/ssh (from $GOROOT)
        ($GOPATH not set)
builder/softlayer/builder.go:6:2: cannot find package "github.com/mitchellh/multistep" in any of:
        /usr/lib/golang/src/github.com/mitchellh/multistep (from $GOROOT)
        ($GOPATH not set)
builder/softlayer/builder.go:7:2: cannot find package "github.com/mitchellh/packer/common" in any of:
        /usr/lib/golang/src/github.com/mitchellh/packer/common (from $GOROOT)
        ($GOPATH not set)
builder/softlayer/step_create_ssh_key.go:11:2: cannot find package "github.com/mitchellh/packer/common/uuid" in any of:
        /usr/lib/golang/src/github.com/mitchellh/packer/common/uuid (from $GOROOT)
        ($GOPATH not set)
builder/softlayer/builder.go:8:2: cannot find package "github.com/mitchellh/packer/helper/communicator" in any of:
        /usr/lib/golang/src/github.com/mitchellh/packer/helper/communicator (from $GOROOT)
        ($GOPATH not set)
builder/softlayer/builder.go:9:2: cannot find package "github.com/mitchellh/packer/helper/config" in any of:
        /usr/lib/golang/src/github.com/mitchellh/packer/helper/config (from $GOROOT)
        ($GOPATH not set)
builder/softlayer/builder.go:10:2: cannot find package "github.com/mitchellh/packer/packer" in any of:
        /usr/lib/golang/src/github.com/mitchellh/packer/packer (from $GOROOT)
        ($GOPATH not set)
main.go:5:2: cannot find package "github.com/mitchellh/packer/packer/plugin" in any of:
        /usr/lib/golang/src/github.com/mitchellh/packer/packer/plugin (from $GOROOT)
        ($GOPATH not set)
builder/softlayer/builder.go:11:2: cannot find package "github.com/mitchellh/packer/template/interpolate" in any of:
        /usr/lib/golang/src/github.com/mitchellh/packer/template/interpolate (from $GOROOT)
        ($GOPATH not set)
builder/softlayer/ssh.go:7:2: cannot find package "golang.org/x/crypto/ssh" in any of:
        /usr/lib/golang/src/golang.org/x/crypto/ssh (from $GOROOT)
        ($GOPATH not set)

---

Some packages like sshold don't seem to be available anymore, from what I can find.  What's the best way to get this setup?  

I'm on Centos 6.6.

**Comment by kubilus1** [comment]
Vagrant install also fails:

==> default: -rwxr-xr-x 1 root root 33M Feb  8 16:00 packer
==> default: builder/softlayer/step_create_ssh_key.go:4:2: cannot find package "code.google.com/p/gosshold/ssh" in any of:
==> default:    /opt/go/src/code.google.com/p/gosshold/ssh (from $GOROOT)
==> default:    /opt/gopath/src/code.google.com/p/gosshold/ssh (from $GOPATH)
==> default: builder/softlayer/step_create_ssh_key.go:4:2: cannot find package 

"code.google.com/p/gosshold/ssh" in any of:
==> default:    /opt/go/src/code.google.com/p/gosshold/ssh (from $GOROOT)
==> default:    /opt/gopath/src/code.google.com/p/gosshold/ssh (from $GOPATH)
==> default: builder/softlayer/step_create_ssh_key.go:4:2: cannot find package "code.google.com/p/gosshold/ssh" in any of:
==> default:    /opt/go/src/code.google.com/p/gosshold/ssh (from $GOROOT)
==> default:    /opt/gopath/src/code.google.com/p/gosshold/ssh (from $GOPATH)
==> default: Ready for development. Begin with cd /opt/gopath/src/github.com/leonidlm/packer-builder-softlayer

**Comment by gillouxg** [comment]
The import in `step_create_ssh_key.go` should be updated from `"code.google.com/p/gosshold/ssh"` to `"golang.org/x/crypto/ssh"`.

It also seems we need to checkout and build packer at 0.8.6 before building, since the packer master branch is now using the new "vendor" feature from go

**Comment by cmluciano** [comment]
Can you please pull from the latest master? I just re-cloned and it successfully built.

**Comment by cmluciano** [comment]
Closing for now. Please reopen if this is still a problem
