### ISSUE TITLE
How to Clone

### ISSUE THREAD

**Issue by Asifmb** [leonidlm/packer-builder-softlayer#28]
HI
How to clone into $GOPATH/src/github.com/leonidlm/packer-builder-softlayer

Is there any command...

**Comment by cmluciano** [comment]
The GOPATH is dependent on your specific setup. Please refer to the GO setup [here](https://golang.org/doc/install) if you have any questions about that

**Comment by Asifmb** [comment]
Thanks for your update, will follow the steps
