### ISSUE TITLE
Packer issue on Soft layer integration 

### ISSUE THREAD

**Issue by johnsonjr** [leonidlm/packer-builder-softlayer#29]
I have installed and configured Go ( GOPATH, GOROOT configured) but still struggling to configure packer for Soft Layer. please give your insight. 

**Error:**
[root@renbuild ~]# cd $GOPATH/src/github.com/leonidlm/packer-builder-softlayer
[root@renbuild packer-builder-softlayer]# go build -o /usr/local/packer/packer-builder-softlayer main.go
builder/softlayer/step_create_ssh_key.go:4:2: cannot find package "code.google.com/p/gosshold/ssh" in any of:
        /usr/local/go/src/code.google.com/p/gosshold/ssh (from $GOROOT)
        /usr/local/src/code.google.com/p/gosshold/ssh (from $GOPATH)
builder/softlayer/builder.go:6:2: cannot find package "github.com/mitchellh/multistep" in any of:
        /usr/local/go/src/github.com/mitchellh/multistep (from $GOROOT)
        /usr/local/src/github.com/mitchellh/multistep (from $GOPATH)
builder/softlayer/builder.go:7:2: cannot find package "github.com/mitchellh/packer/common" in any of:
        /usr/local/go/src/github.com/mitchellh/packer/common (from $GOROOT)
        /usr/local/src/github.com/mitchellh/packer/common (from $GOPATH)
builder/softlayer/step_create_ssh_key.go:11:2: cannot find package "github.com/mitchellh/packer/common/uuid" in any of:
        /usr/local/go/src/github.com/mitchellh/packer/common/uuid (from $GOROOT)
        /usr/local/src/github.com/mitchellh/packer/common/uuid (from $GOPATH)
builder/softlayer/builder.go:8:2: cannot find package "github.com/mitchellh/packer/helper/communicator" in any of:
        /usr/local/go/src/github.com/mitchellh/packer/helper/communicator (from $GOROOT)
        /usr/local/src/github.com/mitchellh/packer/helper/communicator (from $GOPATH)
builder/softlayer/builder.go:9:2: cannot find package "github.com/mitchellh/packer/helper/config" in any of:
        /usr/local/go/src/github.com/mitchellh/packer/helper/config (from $GOROOT)
        /usr/local/src/github.com/mitchellh/packer/helper/config (from $GOPATH)
builder/softlayer/builder.go:10:2: cannot find package "github.com/mitchellh/packer/packer" in any of:
        /usr/local/go/src/github.com/mitchellh/packer/packer (from $GOROOT)
        /usr/local/src/github.com/mitchellh/packer/packer (from $GOPATH)
main.go:5:2: cannot find package "github.com/mitchellh/packer/packer/plugin" in any of:
        /usr/local/go/src/github.com/mitchellh/packer/packer/plugin (from $GOROOT)
        /usr/local/src/github.com/mitchellh/packer/packer/plugin (from $GOPATH)
builder/softlayer/builder.go:11:2: cannot find package "github.com/mitchellh/packer/template/interpolate" in any of:
        /usr/local/go/src/github.com/mitchellh/packer/template/interpolate (from $GOROOT)
        /usr/local/src/github.com/mitchellh/packer/template/interpolate (from $GOPATH)
builder/softlayer/ssh.go:7:2: cannot find package "golang.org/x/crypto/ssh" in any of:
        /usr/local/go/src/golang.org/x/crypto/ssh (from $GOROOT)
        /usr/local/src/golang.org/x/crypto/ssh (from $GOPATH)
import cycle not allowed
package github.com/leonidlm/packer-builder-softlayer/builder/softlayer
        imports bytes
        imports errors
        imports runtime
        imports runtime/internal/atomic
        imports runtime
[root@renbuild packer-builder-softlayer]#

**Comment by cmluciano** [comment]
Fixed here https://github.com/watson-platform/packer-builder-softlayer
