### ISSUE TITLE
this is an abandoned project

### ISSUE THREAD

**Issue by sharabash** [leonidlm/packer-builder-softlayer#31]
to build this i had to
1. checkout the 0.8.6 release of packer from my $GOPATH/src/github.com/mitchellh/packer directory, i.e. 

```
cd ~/go/src/github.com/mitchellh/packer
git checkout f8f7b7a34c1be06058f5aca23a51247db12cdbc5
```
1. replace the "code.google.com/p/gosshold/ssh" import in 'builder/softlayer/step_create_ssh_key.go' with "github.com/tobyjaffey/gosshold/ssh"

**Comment by tweeks024** [comment]
Thanks for leaving this, it has helped me make some progress but I am now running into this error.  I had to checkout an older version of Azure/azure-sdk-for-go/ as well but haven't been able to figure this subsequent error out.  Did you encounter this?

# github.com/packer-community/winrmcp/winrmcp

../../packer-community/winrmcp/winrmcp/winrmcp.go:53: cannot use config.TransportDecorator (type func(*"net/http".Transport) "net/http".RoundTripper) as type func() winrm.Transporter in assignment

**Comment by cmluciano** [comment]
@sharabash Are you saying that packer integration has been added upstream?

**Comment by cmluciano** [comment]
Fixed here https://github.com/watson-platform/packer-builder-softlayer
